# Generated by Django 5.0 on 2026-02-06 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0037_product_qr_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
    ]
