# Generated by Django 5.0 on 2026-02-06 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0038_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='controle',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
