# Generated by Django 5.0 on 2026-02-06 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0039_controle_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controle',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_code/'),
        ),
    ]
